### ISSUE TITLE
Pure Storage FlashArray End to End Workflows.wfdx import error UCSD6.0

### ISSUE THREAD

**Issue by cswaters1** [purestorage/ucs-director-plugin#10]
When I try and import the Pure Storage FlashArray End to End Workflows.wfdx file I get a java exception error and am unable to import the wfdx file into UCSD6.0.

**Workflow Import Thread Exception**

Can anyone help?

**Comment by saif-cl0ud** [comment]
Check the latest version of workflows for UCSD 6.0
